version: '3'

networks:
  trainer:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1001
    networks:
      - trainer

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jacquesvst@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1001
    networks:
      - trainer

  api:
    image: 'api'
    build: .
    container_name: api
    environment:
      - DATABASE_HOST=postgres
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - trainer
